name: GPCR_machiine_learning
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.12.*
  - scikit-learn=1.4.*
  - matplotlib=3.8.*
  - seaborn=0.13.*
  - shap=0.45.*
  - umap-learn=0.5.*
  - imbalanced-learn=0.12.*
  - ipython=8.*
  - jupyterlab=4.*
  - pip

  - pip:
      - xgboost==2.1.1
